In [7]:
import pandas as pd
import numpy as np

print("TP Data Mining - Pipeline KDD")

TP Data Mining - Pipeline KDD

# TP1 - Data Collection
## KDD Process
### Student : Ardo

In [8]:
import pandas as pd

path = "../data/student-mat.csv"

df = pd.read_csv(path, sep=",")

df.head()

,STUDENT ID,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STUDENT ID  145 non-null    object
 1   1           145 non-null    int64
 2   2           145 non-null    int64
 3   3           145 non-null    int64
 4   4           145 non-null    int64
 5   5           145 non-null    int64
 6   6           145 non-null    int64
 7   7           145 non-null    int64
 8   8           145 non-null    int64
 9   9           145 non-null    int64
 10  10          145 non-null    int64
 11  11          145 non-null    int64
 12  12          145 non-null    int64
 13  13          145 non-null    int64
 14  14          145 non-null    int64
 15  15          145 non-null    int64
 16  16          145 non-null    int64
 17  17          145 non-null    int64
 18  18          145 non-null    int64
 19  19          145 non-null    int64
 20  20          145 non-null    int64
 21  21          145 non-null    int64
 22  22          145 non-null    int64
 23  23          145 non-null    int64
 24  24          145 non-null    int64
 25  25          145 non-null    int64
 26  26          145 non-null    int64
 27  27          145 non-null    int64
 28  28          145 non-null    int64
 29  29          145 non-null    int64
 30  30          145 non-null    int64
 31  COURSE ID   145 non-null    int64
 32  GRADE       145 non-null    int64
dtypes: int64(32), object(1)
memory usage: 37.5+ KB

In [10]:
df.describe()

,1,2,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,COURSE ID,GRADE
count,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,...,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000
mean,1.620690,1.600000,1.944828,3.572414,1.662069,1.600000,1.579310,1.627586,1.620690,1.731034,...,1.337931,1.165517,2.544828,2.055172,2.393103,1.806897,3.124138,2.724138,4.131034,3.227586
std,0.613154,0.491596,0.537216,0.805750,0.474644,0.491596,0.495381,1.020245,1.061112,0.783999,...,0.614870,0.408483,0.564940,0.674736,0.604343,0.810492,1.301083,0.916536,3.260145,2.197678
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000
50%,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,...,1.000000,1.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000
75%,2.000000,2.000000,2.000000,4.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,1.000000,3.000000,3.000000,3.000000,2.000000,4.000000,3.000000,7.000000,5.000000
max,3.000000,2.000000,3.000000,5.000000,2.000000,2.000000,2.000000,5.000000,4.000000,4.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,5.000000,4.000000,9.000000,7.000000

In [11]:
df["GRADE"].describe()

count    145.000000
mean       3.227586
std        2.197678
min        0.000000
25%        1.000000
50%        3.000000
75%        5.000000
max        7.000000
Name: GRADE, dtype: float64

Merci pour votre Attention fin du TP_1

In [12]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp zbook\anaconda3\envs\tp_data_mining\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\hp zbook\anaconda3\envs\tp_data_mining\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.