Manipulation de formats semi-structurés (JSON & Excel)

In [4]:
import pandas as pd

df_movies = pd.read_json("../data/movies.json")

df_movies.head()

,title,year,cast,genres,href,extract,thumbnail,thumbnail_width,thumbnail_height
0,After Dark in Central Park,1900,[],[],None,NaN,NaN,NaN,NaN
1,Boarding School Girls' Pajama Parade,1900,[],[],None,NaN,NaN,NaN,NaN
2,Buffalo Bill's Wild West Parad,1900,[],[],None,NaN,NaN,NaN,NaN
3,Caught,1900,[],[],None,NaN,NaN,NaN,NaN
4,Clowns Spinning Hats,1900,[],[Silent],Clowns_Spinning_Hats,Clowns Spinning Hats is a black-and-white sile...,NaN,NaN,NaN

In [5]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36273 entries, 0 to 36272
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             36273 non-null  object
 1   year              36273 non-null  int64
 2   cast              36273 non-null  object
 3   genres            36273 non-null  object
 4   href              34540 non-null  object
 5   extract           34532 non-null  object
 6   thumbnail         30368 non-null  object
 7   thumbnail_width   30368 non-null  float64
 8   thumbnail_height  30368 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 2.5+ MB

Si le fichier est au format "JSON Lines", quel argument devez-vous ajouter ?
Il faut ajouter l'argument lines=True, ce qui donne :
 
pd.read_json('fichier.json', lines=True).




Données de Gestion (Excel)

In [6]:
import pandas as pd
df_excel = pd.read_excel("../data/Financial Sample.xlsx")
df_excel.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014